### ISSUE TITLE
errors when installing

### ISSUE THREAD

**Issue by VerserVarlin** [Weisl/simple_collider#508]
what version of blender is this for, it errors when i try to install. i use v4.1.1
![image_2024-11-09_133938196](https://github.com/user-attachments/assets/c1e21040-572f-467a-a91e-7cd80fe6d464)

**Comment by Weisl** [comment]
The officially supported version for Simple Collider can be downloaded from Blender Market and Gumroad. What you are downloading from here is the development branch that might not work out of the box. 
Versions on the stores are tested and properly packaged.
